// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site.*, every other .ts → FnsRegistry.site.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        site: {
            $avail_notExample: typeof import("./$avail_notExample").default;
            $section_capabilityGrid: typeof import("./$section_capabilityGrid").default;
            $section_cld: typeof import("./$section_cld").default;
            $section_concepts: typeof import("./$section_concepts").default;
            $section_csReferences: typeof import("./$section_csReferences").default;
            $section_description: typeof import("./$section_description").default;
            $section_expansion: typeof import("./$section_expansion").default;
            $section_formalViews: typeof import("./$section_formalViews").default;
            $section_meta: typeof import("./$section_meta").default;
            $section_narrative: typeof import("./$section_narrative").default;
            $section_notes: typeof import("./$section_notes").default;
            $section_quickStart: typeof import("./$section_quickStart").default;
            $section_searchParamDetail: typeof import("./$section_searchParamDetail").default;
            $section_usages: typeof import("./$section_usages").default;
            $section_vsReferences: typeof import("./$section_vsReferences").default;
            applyBlocks: typeof import("./applyBlocks").default;
            artifactTable: typeof import("./artifactTable").default;
            bindingsTable: typeof import("./bindingsTable").default;
            blockDefaults: typeof import("./blockDefaults").default;
            buildInfoBanner: typeof import("./buildInfoBanner").default;
            bundleNarrative: typeof import("./bundleNarrative").default;
            bytes: typeof import("./bytes").default;
            canonicalMeta: typeof import("./canonicalMeta").default;
            canonicalResource: typeof import("./canonicalResource").default;
            canonicalTabStrip: typeof import("./canonicalTabStrip").default;
            codeSystemUsage: typeof import("./codeSystemUsage").default;
            companionPages: typeof import("./companionPages").default;
            conceptTable: typeof import("./conceptTable").default;
            constraintsTable: typeof import("./constraintsTable").default;
            detailTable: typeof import("./detailTable").default;
            displayFor: typeof import("./displayFor").default;
            elementRow: typeof import("./elementRow").default;
            elementTable: typeof import("./elementTable").default;
            enable: typeof import("./enable").default;
            examplesForProfile: typeof import("./examplesForProfile").default;
            expandIncludes: typeof import("./expandIncludes").default;
            expectationOf: typeof import("./expectationOf").default;
            featureOn: typeof import("./featureOn").default;
            fhirValue: typeof import("./fhirValue").default;
            flagLegend: typeof import("./flagLegend").default;
            flagsCell: typeof import("./flagsCell").default;
            formatCard: typeof import("./formatCard").default;
            formatChips: typeof import("./formatChips").default;
            formatPath: typeof import("./formatPath").default;
            generateNarrative: typeof import("./generateNarrative").default;
            handleHotUpdate: typeof import("./handleHotUpdate").default;
            highlightBlocks: typeof import("./highlightBlocks").default;
            highlightCode: typeof import("./highlightCode").default;
            htmlEscape: typeof import("./htmlEscape").default;
            humanType: typeof import("./humanType").default;
            idOf: typeof import("./idOf").default;
            injectRefLinks: typeof import("./injectRefLinks").default;
            introBlock: typeof import("./introBlock").default;
            jsonBlock: typeof import("./jsonBlock").default;
            layout: typeof import("./layout").default;
            linkCanonical: typeof import("./linkCanonical").default;
            linkType: typeof import("./linkType").default;
            loadIntroNotes: typeof import("./loadIntroNotes").default;
            loadPagecontent: typeof import("./loadPagecontent").default;
            mdInline: typeof import("./mdInline").default;
            mdToHtml: typeof import("./mdToHtml").default;
            mergeTabs: typeof import("./mergeTabs").default;
            metaDl: typeof import("./metaDl").default;
            navActiveScript: typeof import("./navActiveScript").default;
            notesBlock: typeof import("./notesBlock").default;
            notesFor: typeof import("./notesFor").default;
            order: typeof import("./order").default;
            pageHeader: typeof import("./pageHeader").default;
            pageHref: typeof import("./pageHref").default;
            pageToc: typeof import("./pageToc").default;
            parseIal: typeof import("./parseIal").default;
            pillType: typeof import("./pillType").default;
            profileTabs: typeof import("./profileTabs").default;
            quickStartTable: typeof import("./quickStartTable").default;
            renderArtifacts: typeof import("./renderArtifacts").default;
            renderBreadcrumb: typeof import("./renderBreadcrumb").default;
            renderCanonical: typeof import("./renderCanonical").default;
            renderDefinitionsPage: typeof import("./renderDefinitionsPage").default;
            renderExamplesPage: typeof import("./renderExamplesPage").default;
            renderIndex: typeof import("./renderIndex").default;
            renderLanding: typeof import("./renderLanding").default;
            renderMappingsPage: typeof import("./renderMappingsPage").default;
            renderPage: typeof import("./renderPage").default;
            renderProfileJsonPage: typeof import("./renderProfileJsonPage").default;
            renderResource: typeof import("./renderResource").default;
            renderResourceJsonPage: typeof import("./renderResourceJsonPage").default;
            renderSidebarGroup: typeof import("./renderSidebarGroup").default;
            renderValueSetJsonPage: typeof import("./renderValueSetJsonPage").default;
            sdCompanionPages: typeof import("./sdCompanionPages").default;
            sdHrefs: typeof import("./sdHrefs").default;
            sdListTable: typeof import("./sdListTable").default;
            searchParamsFor: typeof import("./searchParamsFor").default;
            sectionDefaults: typeof import("./sectionDefaults").default;
            sectionHeader: typeof import("./sectionHeader").default;
            sectionsFor: typeof import("./sectionsFor").default;
            shortLabel: typeof import("./shortLabel").default;
            sidebar: typeof import("./sidebar").default;
            stripUnrenderedLiquid: typeof import("./stripUnrenderedLiquid").default;
            tabDefaults: typeof import("./tabDefaults").default;
            tabHashScript: typeof import("./tabHashScript").default;
            tabLinks: typeof import("./tabLinks").default;
            tabsFor: typeof import("./tabsFor").default;
            tagBindingStrength: typeof import("./tagBindingStrength").default;
            tagMS: typeof import("./tagMS").default;
            titleOf: typeof import("./titleOf").default;
            topBar: typeof import("./topBar").default;
            treeIndent: typeof import("./treeIndent").default;
            urlVersionStrip: typeof import("./urlVersionStrip").default;
            usagesOf: typeof import("./usagesOf").default;
            valueSetUsage: typeof import("./valueSetUsage").default;
            vsCld: typeof import("./vsCld").default;
            vsCompanionPages: typeof import("./vsCompanionPages").default;
            vsExpand: typeof import("./vsExpand").default;
            warmHighlighter: typeof import("./warmHighlighter").default;
            watchPaths: typeof import("./watchPaths").default;
            writeBundle: typeof import("./writeBundle").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace site {
            type BlockDescriptor = import("./$type_BlockDescriptor").BlockDescriptor;
            type Ial = import("./$type_Ial").Ial;
            type RenderCtx = import("./$type_RenderCtx").RenderCtx;
            type SdHrefs = import("./$type_SdHrefs").SdHrefs;
            type SiteOpts = import("./$type_SiteOpts").SiteOpts;
            type TabDescriptor = import("./$type_TabDescriptor").TabDescriptor;
            type TabMergeSpec = import("./$type_TabMergeSpec").TabMergeSpec;
        }
    }
}
export {};
