// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site.*, every other .ts → FnsRegistry.site.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        site: {
            $render_CodeSystem: typeof import("./$render_CodeSystem").default;
            $render_default: typeof import("./$render_default").default;
            $render_StructureDefinition: typeof import("./$render_StructureDefinition").default;
            $render_ValueSet: typeof import("./$render_ValueSet").default;
            artifactTable: typeof import("./artifactTable").default;
            bindingsTable: typeof import("./bindingsTable").default;
            buildInfoBanner: typeof import("./buildInfoBanner").default;
            bytes: typeof import("./bytes").default;
            constraintsTable: typeof import("./constraintsTable").default;
            detailTable: typeof import("./detailTable").default;
            elementRow: typeof import("./elementRow").default;
            elementTable: typeof import("./elementTable").default;
            examplesForProfile: typeof import("./examplesForProfile").default;
            flagLegend: typeof import("./flagLegend").default;
            flagsCell: typeof import("./flagsCell").default;
            formatCard: typeof import("./formatCard").default;
            formatChips: typeof import("./formatChips").default;
            formatPath: typeof import("./formatPath").default;
            handleHotUpdate: typeof import("./handleHotUpdate").default;
            highlightCode: typeof import("./highlightCode").default;
            htmlEscape: typeof import("./htmlEscape").default;
            humanType: typeof import("./humanType").default;
            idOf: typeof import("./idOf").default;
            introBlock: typeof import("./introBlock").default;
            jsonBlock: typeof import("./jsonBlock").default;
            layout: typeof import("./layout").default;
            linkCanonical: typeof import("./linkCanonical").default;
            linkType: typeof import("./linkType").default;
            loadIntroNotes: typeof import("./loadIntroNotes").default;
            loadPagecontent: typeof import("./loadPagecontent").default;
            metaDl: typeof import("./metaDl").default;
            navActiveScript: typeof import("./navActiveScript").default;
            notesBlock: typeof import("./notesBlock").default;
            notesFor: typeof import("./notesFor").default;
            order: typeof import("./order").default;
            pageHeader: typeof import("./pageHeader").default;
            pageHref: typeof import("./pageHref").default;
            pillType: typeof import("./pillType").default;
            profileTabs: typeof import("./profileTabs").default;
            quickStartTable: typeof import("./quickStartTable").default;
            renderArtifacts: typeof import("./renderArtifacts").default;
            renderBreadcrumb: typeof import("./renderBreadcrumb").default;
            renderIndex: typeof import("./renderIndex").default;
            renderLanding: typeof import("./renderLanding").default;
            renderPage: typeof import("./renderPage").default;
            renderResource: typeof import("./renderResource").default;
            renderSidebarGroup: typeof import("./renderSidebarGroup").default;
            searchParamsFor: typeof import("./searchParamsFor").default;
            sectionHeader: typeof import("./sectionHeader").default;
            shortLabel: typeof import("./shortLabel").default;
            sidebar: typeof import("./sidebar").default;
            stripUnrenderedLiquid: typeof import("./stripUnrenderedLiquid").default;
            tabHashScript: typeof import("./tabHashScript").default;
            tagBindingStrength: typeof import("./tagBindingStrength").default;
            tagMS: typeof import("./tagMS").default;
            titleOf: typeof import("./titleOf").default;
            topBar: typeof import("./topBar").default;
            treeIndent: typeof import("./treeIndent").default;
            urlVersionStrip: typeof import("./urlVersionStrip").default;
            usagesOf: typeof import("./usagesOf").default;
            watchPaths: typeof import("./watchPaths").default;
            writeBundle: typeof import("./writeBundle").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace site {
            type RenderCtx = import("./$type_RenderCtx").RenderCtx;
            type SiteOpts = import("./$type_SiteOpts").SiteOpts;
        }
    }
}
export {};
