// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.capability.*, every other .ts → FnsRegistry.capability.*

declare global {
    interface FnsRegistry {
        capability: {
            $section_capabilityGrid: typeof import("./$section_capabilityGrid").default;
            $section_searchParamDetail: typeof import("./$section_searchParamDetail").default;
            expectationOf: typeof import("./expectationOf").default;
        };
    }

    namespace types {
        namespace capability {
        }
    }
}
export {};
