// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.capability.*, every other .ts → FnsRegistry.capability.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        capability: {
            $section_capabilityGrid: typeof import("./$section_capabilityGrid").default;
            $section_searchParamDetail: typeof import("./$section_searchParamDetail").default;
            expectationOf: typeof import("./expectationOf").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace capability {
        }
    }
}
export {};
