// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_capability.*, every other .ts → FnsRegistry.site_capability.*

declare global {
    interface FnsRegistry {
        site_capability: {
            $section_capabilityGrid: typeof import("./$section_capabilityGrid").default;
            $section_searchParamDetail: typeof import("./$section_searchParamDetail").default;
            expectationOf: typeof import("./expectationOf").default;
        };
    }

    namespace types {
        namespace site_capability {
        }
    }
}
export {};
