// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_core.*, every other .ts → FnsRegistry.site_core.*

declare global {
    // The one ctx: the engine PluginContext + the flat-ns fn registry.
    type Context = types.fcc.PluginContext & { fns: FnsRegistry };

    interface FnsRegistry {
        site_core: {
            $avail_notExample: typeof import("./$avail_notExample").default;
            $route_examplesZip: typeof import("./$route_examplesZip").default;
            $route_extensions: typeof import("./$route_extensions").default;
            $route_qa: typeof import("./$route_qa").default;
            $route_searchParameters: typeof import("./$route_searchParameters").default;
            $section_description: typeof import("./$section_description").default;
            $section_md: typeof import("./$section_md").default;
            $section_notes: typeof import("./$section_notes").default;
            buildInfoBanner: typeof import("./buildInfoBanner").default;
            buildRoutes: typeof import("./buildRoutes").default;
            bytes: typeof import("./bytes").default;
            canonicalMeta: typeof import("./canonicalMeta").default;
            canonicalResource: typeof import("./canonicalResource").default;
            canonicalTabStrip: typeof import("./canonicalTabStrip").default;
            companionPages: typeof import("./companionPages").default;
            composeSections: typeof import("./composeSections").default;
            dataTable: typeof import("./dataTable").default;
            derivePages: typeof import("./derivePages").default;
            enable: typeof import("./enable").default;
            featureOn: typeof import("./featureOn").default;
            formatCard: typeof import("./formatCard").default;
            handleHotUpdate: typeof import("./handleHotUpdate").default;
            htmlEscape: typeof import("./htmlEscape").default;
            humanType: typeof import("./humanType").default;
            idOf: typeof import("./idOf").default;
            introBlock: typeof import("./introBlock").default;
            jsonBlock: typeof import("./jsonBlock").default;
            layout: typeof import("./layout").default;
            linkCanonical: typeof import("./linkCanonical").default;
            linkGrid: typeof import("./linkGrid").default;
            linkType: typeof import("./linkType").default;
            loadIntroNotes: typeof import("./loadIntroNotes").default;
            mergeTabs: typeof import("./mergeTabs").default;
            metaDl: typeof import("./metaDl").default;
            navActiveScript: typeof import("./navActiveScript").default;
            notesFor: typeof import("./notesFor").default;
            order: typeof import("./order").default;
            pageHeader: typeof import("./pageHeader").default;
            pageHref: typeof import("./pageHref").default;
            pillType: typeof import("./pillType").default;
            renderBreadcrumb: typeof import("./renderBreadcrumb").default;
            renderCanonical: typeof import("./renderCanonical").default;
            renderResource: typeof import("./renderResource").default;
            renderResourceJsonPage: typeof import("./renderResourceJsonPage").default;
            renderSidebarGroup: typeof import("./renderSidebarGroup").default;
            resolveFn: typeof import("./resolveFn").default;
            sectionDefaults: typeof import("./sectionDefaults").default;
            sectionHeader: typeof import("./sectionHeader").default;
            sectionsFor: typeof import("./sectionsFor").default;
            shortLabel: typeof import("./shortLabel").default;
            sidebar: typeof import("./sidebar").default;
            statusBadge: typeof import("./statusBadge").default;
            tabDefaults: typeof import("./tabDefaults").default;
            tabLinks: typeof import("./tabLinks").default;
            tabsFor: typeof import("./tabsFor").default;
            tagBindingStrength: typeof import("./tagBindingStrength").default;
            titleOf: typeof import("./titleOf").default;
            topBar: typeof import("./topBar").default;
            urlVersionStrip: typeof import("./urlVersionStrip").default;
            watchPaths: typeof import("./watchPaths").default;
            writeBundle: typeof import("./writeBundle").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace site_core {
            type RenderCtx = import("./$type_RenderCtx").RenderCtx;
            type Route = import("./$type_Route").Route;
            type RouteDef = import("./$type_RouteDef").RouteDef;
            type SiteOpts = import("./$type_SiteOpts").SiteOpts;
            type TabDescriptor = import("./$type_TabDescriptor").TabDescriptor;
            type TabMergeSpec = import("./$type_TabMergeSpec").TabMergeSpec;
        }
    }
}
export {};
