// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_md.*, every other .ts → FnsRegistry.site_md.*

declare global {
    interface FnsRegistry {
        site_md: {
            anchorHeadings: typeof import("./anchorHeadings").default;
            applyBlocks: typeof import("./applyBlocks").default;
            blockDefaults: typeof import("./blockDefaults").default;
            expandIncludes: typeof import("./expandIncludes").default;
            highlightBlocks: typeof import("./highlightBlocks").default;
            highlightCode: typeof import("./highlightCode").default;
            injectRefLinks: typeof import("./injectRefLinks").default;
            lrefDependency: typeof import("./lrefDependency").default;
            lrefFhirPath: typeof import("./lrefFhirPath").default;
            lrefMap: typeof import("./lrefMap").default;
            lrefResource: typeof import("./lrefResource").default;
            mdInline: typeof import("./mdInline").default;
            mdToHtml: typeof import("./mdToHtml").default;
            parseIal: typeof import("./parseIal").default;
            sanitizeHtml: typeof import("./sanitizeHtml").default;
            sdListTable: typeof import("./sdListTable").default;
            stripUnrenderedLiquid: typeof import("./stripUnrenderedLiquid").default;
            warmHighlighter: typeof import("./warmHighlighter").default;
        };
    }

    namespace types {
        namespace site_md {
            type BlockDescriptor = import("./$type_BlockDescriptor").BlockDescriptor;
            type Ial = import("./$type_Ial").Ial;
        }
    }
}
export {};
