// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.artifacts.*, every other .ts → FnsRegistry.artifacts.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        artifacts: {
            artifactTable: typeof import("./artifactTable").default;
            loadPagecontent: typeof import("./loadPagecontent").default;
            pageToc: typeof import("./pageToc").default;
            renderArtifacts: typeof import("./renderArtifacts").default;
            renderIndex: typeof import("./renderIndex").default;
            renderLanding: typeof import("./renderLanding").default;
            renderPage: typeof import("./renderPage").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace artifacts {
        }
    }
}
export {};
