// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.narrative.*, every other .ts → FnsRegistry.narrative.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        narrative: {
            $section_meta: typeof import("./$section_meta").default;
            $section_narrative: typeof import("./$section_narrative").default;
            bundleNarrative: typeof import("./bundleNarrative").default;
            fhirValue: typeof import("./fhirValue").default;
            generateNarrative: typeof import("./generateNarrative").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace narrative {
        }
    }
}
export {};
