// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.menu.*, every other .ts → FnsRegistry.menu.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        menu: {
            buildStart: typeof import("./buildStart").default;
            htmlEscape: typeof import("./htmlEscape").default;
            parseMenu: typeof import("./parseMenu").default;
            renderMenu: typeof import("./renderMenu").default;
            renderMenuItem: typeof import("./renderMenuItem").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace menu {
            type MenuNode = import("./$type_MenuNode").MenuNode;
            type MenuOpts = import("./$type_MenuOpts").MenuOpts;
        }
    }
}
export {};
