// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.menu.*, every other .ts → FnsRegistry.menu.*

declare global {
    interface FnsRegistry {
        menu: {
            buildStart: typeof import("./buildStart").default;
            htmlEscape: typeof import("./htmlEscape").default;
            parseMenu: typeof import("./parseMenu").default;
            renderMenu: typeof import("./renderMenu").default;
            renderMenuItem: typeof import("./renderMenuItem").default;
        };
    }

    namespace types {
        namespace menu {
            type MenuNode = import("./$type_MenuNode").MenuNode;
            type MenuOpts = import("./$type_MenuOpts").MenuOpts;
        }
    }
}
export {};
