// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_artifacts.*, every other .ts → FnsRegistry.site_artifacts.*

declare global {
    interface FnsRegistry {
        site_artifacts: {
            artifactTable: typeof import("./artifactTable").default;
            loadPagecontent: typeof import("./loadPagecontent").default;
            pageToc: typeof import("./pageToc").default;
            renderArtifacts: typeof import("./renderArtifacts").default;
            renderIndex: typeof import("./renderIndex").default;
            renderLanding: typeof import("./renderLanding").default;
            renderPage: typeof import("./renderPage").default;
        };
    }

    namespace types {
        namespace site_artifacts {
        }
    }
}
export {};
