// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_profile.*, every other .ts → FnsRegistry.site_profile.*

declare global {
    interface FnsRegistry {
        site_profile: {
            $section_formalViews: typeof import("./$section_formalViews").default;
            $section_quickStart: typeof import("./$section_quickStart").default;
            $section_usages: typeof import("./$section_usages").default;
            bindingsTable: typeof import("./bindingsTable").default;
            constraintsTable: typeof import("./constraintsTable").default;
            detailTable: typeof import("./detailTable").default;
            elementRow: typeof import("./elementRow").default;
            elementTable: typeof import("./elementTable").default;
            examplesForProfile: typeof import("./examplesForProfile").default;
            flagLegend: typeof import("./flagLegend").default;
            flagsCell: typeof import("./flagsCell").default;
            profileTabs: typeof import("./profileTabs").default;
            quickStartTable: typeof import("./quickStartTable").default;
            renderDefinitionsPage: typeof import("./renderDefinitionsPage").default;
            renderExamplesPage: typeof import("./renderExamplesPage").default;
            renderMappingsPage: typeof import("./renderMappingsPage").default;
            renderProfileJsonPage: typeof import("./renderProfileJsonPage").default;
            sdHrefs: typeof import("./sdHrefs").default;
            searchParamsFor: typeof import("./searchParamsFor").default;
            tabHashScript: typeof import("./tabHashScript").default;
            treeIndent: typeof import("./treeIndent").default;
            usagesOf: typeof import("./usagesOf").default;
        };
    }

    namespace types {
        namespace site_profile {
            type SdHrefs = import("./$type_SdHrefs").SdHrefs;
        }
    }
}
export {};
