// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_narrative.*, every other .ts → FnsRegistry.site_narrative.*

declare global {
    interface FnsRegistry {
        site_narrative: {
            $section_meta: typeof import("./$section_meta").default;
            $section_narrative: typeof import("./$section_narrative").default;
            bundleNarrative: typeof import("./bundleNarrative").default;
            fhirValue: typeof import("./fhirValue").default;
            generateNarrative: typeof import("./generateNarrative").default;
        };
    }

    namespace types {
        namespace site_narrative {
        }
    }
}
export {};
