// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.site_terminology.*, every other .ts → FnsRegistry.site_terminology.*

declare global {
    interface FnsRegistry {
        site_terminology: {
            $section_cld: typeof import("./$section_cld").default;
            $section_concepts: typeof import("./$section_concepts").default;
            $section_csReferences: typeof import("./$section_csReferences").default;
            $section_expansion: typeof import("./$section_expansion").default;
            $section_vsReferences: typeof import("./$section_vsReferences").default;
            codeSystemUsage: typeof import("./codeSystemUsage").default;
            conceptTable: typeof import("./conceptTable").default;
            displayFor: typeof import("./displayFor").default;
            renderValueSetJsonPage: typeof import("./renderValueSetJsonPage").default;
            valueSetUsage: typeof import("./valueSetUsage").default;
            vsCld: typeof import("./vsCld").default;
            vsExpand: typeof import("./vsExpand").default;
        };
    }

    namespace types {
        namespace site_terminology {
        }
    }
}
export {};
