// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.profile.*, every other .ts → FnsRegistry.profile.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        profile: {
            $section_formalViews: typeof import("./$section_formalViews").default;
            $section_quickStart: typeof import("./$section_quickStart").default;
            $section_usages: typeof import("./$section_usages").default;
            bindingsTable: typeof import("./bindingsTable").default;
            constraintsTable: typeof import("./constraintsTable").default;
            detailTable: typeof import("./detailTable").default;
            elementRow: typeof import("./elementRow").default;
            elementTable: typeof import("./elementTable").default;
            examplesForProfile: typeof import("./examplesForProfile").default;
            flagLegend: typeof import("./flagLegend").default;
            flagsCell: typeof import("./flagsCell").default;
            profileTabs: typeof import("./profileTabs").default;
            quickStartTable: typeof import("./quickStartTable").default;
            renderDefinitionsPage: typeof import("./renderDefinitionsPage").default;
            renderExamplesPage: typeof import("./renderExamplesPage").default;
            renderMappingsPage: typeof import("./renderMappingsPage").default;
            renderProfileJsonPage: typeof import("./renderProfileJsonPage").default;
            sdHrefs: typeof import("./sdHrefs").default;
            searchParamsFor: typeof import("./searchParamsFor").default;
            tabHashScript: typeof import("./tabHashScript").default;
            treeIndent: typeof import("./treeIndent").default;
            usagesOf: typeof import("./usagesOf").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace profile {
            type SdHrefs = import("./$type_SdHrefs").SdHrefs;
        }
    }
}
export {};
