// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.md.*, every other .ts → FnsRegistry.md.*

declare global {
    type Context = {
        cfg:     types.fcc.ResolvedConfig;
        target:  types.fcc.Target;
        bundle:  types.fcc.Bundle;
        notes?:  Map<string, { intro?: string; notes?: string }>;
        state:   Record<string, any>;
        env:     Record<string, string | undefined>;
        fns:     FnsRegistry;
    };

    interface FnsRegistry {
        md: {
            applyBlocks: typeof import("./applyBlocks").default;
            blockDefaults: typeof import("./blockDefaults").default;
            expandIncludes: typeof import("./expandIncludes").default;
            highlightBlocks: typeof import("./highlightBlocks").default;
            highlightCode: typeof import("./highlightCode").default;
            injectRefLinks: typeof import("./injectRefLinks").default;
            mdInline: typeof import("./mdInline").default;
            mdToHtml: typeof import("./mdToHtml").default;
            parseIal: typeof import("./parseIal").default;
            sdListTable: typeof import("./sdListTable").default;
            stripUnrenderedLiquid: typeof import("./stripUnrenderedLiquid").default;
            warmHighlighter: typeof import("./warmHighlighter").default;
        };
    }

    namespace types {
        namespace fcc {
            type Bundle = import("fcc").Bundle;
            type Resource = import("fcc").Resource;
            type ResolvedConfig = import("fcc").ResolvedConfig;
            type Target = import("fcc").Target;
            type Plugin = import("fcc").Plugin;
            type PluginContext = import("fcc").PluginContext;
            type HotUpdateContext = import("fcc").HotUpdateContext;
        }
        namespace md {
            type BlockDescriptor = import("./$type_BlockDescriptor").BlockDescriptor;
            type Ial = import("./$type_Ial").Ial;
        }
    }
}
export {};
