// Auto-generated by fcc/gentypes — do not edit.
// Sources: $type_*.ts → types.md.*, every other .ts → FnsRegistry.md.*

declare global {
    interface FnsRegistry {
        md: {
            applyBlocks: typeof import("./applyBlocks").default;
            blockDefaults: typeof import("./blockDefaults").default;
            expandIncludes: typeof import("./expandIncludes").default;
            highlightBlocks: typeof import("./highlightBlocks").default;
            highlightCode: typeof import("./highlightCode").default;
            injectRefLinks: typeof import("./injectRefLinks").default;
            mdInline: typeof import("./mdInline").default;
            mdToHtml: typeof import("./mdToHtml").default;
            parseIal: typeof import("./parseIal").default;
            sanitizeHtml: typeof import("./sanitizeHtml").default;
            sdListTable: typeof import("./sdListTable").default;
            stripUnrenderedLiquid: typeof import("./stripUnrenderedLiquid").default;
            warmHighlighter: typeof import("./warmHighlighter").default;
        };
    }

    namespace types {
        namespace md {
            type BlockDescriptor = import("./$type_BlockDescriptor").BlockDescriptor;
            type Ial = import("./$type_Ial").Ial;
        }
    }
}
export {};
